# --- Basic options --- #

# Name of website
title: Tantrums For Change

# Short description of your site
# description: Turning Trump's Twitter tantrums into something useful.

# Your name to show in the footer
author: Tantrums For Change

# --- List of links in the navigation bar --- #

navbar-links:
  About Us: "about"
  Previous Weeks: "previous"

# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "donations@tantrumsforchange.org"
  twitter: tantrums4change

# --- General options --- #

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "TantrumsForChange.org"

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-170818272-1"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "170818272"

# Google Tag Manager ID
#gtm: ""

# --- Misc --- #

markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
